steps:
  # 環境変数の設定
  - name: node:16.15.0
    entrypoint: yarn
    args: [ "run", "create-env" ]
    env:
      - 'API_KEY=${_API_KEY}'
      - 'SERVICE_DOMAIN=${_SERVICE_DOMAIN}'
  # ビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/blog:$COMMIT_SHA', '.']
  # Container Registryにデプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blog:$COMMIT_SHA']
  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'blog'
      # 誰でもアクセスできるように設定
      - '--allow-unauthenticated'
      - '--image'
      - 'gcr.io/$PROJECT_ID/blog:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
  # 最小起動インスタンスを設定
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'blog'
      - '--min-instances'
      - '1'
      - '--region'
      - 'asia-northeast1'
timeout: "1600s"
#images:
#  - 'gcr.io/$PROJECT_ID/blog:$COMMIT_SHA'
